name: Node.js Package
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: 0
    - run: |
        mkdir -p ~/.gnupg/
        printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key 
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - run: |
        git config --local user.email $GIT_EMAIL
        git config --local user.name $GIT_USER
        git config --local user.signingkey $GPG_KEY_ID
        git config --local commit.gpgsign true
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID}}
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@aleserche.test'
    - run: yarn
    - run: yarn lerna version --yes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: yarn lerna publish from-package --no-verify-access --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Setup .npmrc file to publish to gh registry
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn lerna publish from-package --no-verify-access --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
